### ISSUE TITLE
Question: i2p vs diva exchange

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ArchiveBox/good-karma-kit#10]
Hi,

I noticed that the i2p container is actually made by [diva.exchange](https://www.diva.exchange/en/), a technology using i2p as an anonymity layer to build a banking technology.

Are you certain than this docker container is:
1. safe?
2. actively contributing to i2p instead of just diva.exchange?
3. not better than running a reseeding i3p container?

Thanks

**Comment by pirate** [comment]
PRs welcome to switch it! It was the best container available at the time years ago when I created this, but that may not be the case anymore.

**Comment by thiswillbeyourgithub** [comment]
I arrived at that container:

```yaml

  i2p:
    # the only port you have to expose is the one leading to
    # 12345. It has to support both UDP and TCP.
    # Replace CHANGEME by the same random int between 1024 and 65535
    # Then open the console in your browser to finish the config
    # source: https://geti2p.net/en/download/docker
    image: geti2p/i2p
    volumes:
        - ./i2pconfig:/i2p/.i2p
    ports:
      # - 127.0.0.1:4444:4444/tcp  # HTTP proxy for you
      # - 127.0.0.1:4445:4445/tcp  # HTTPS proxy for you
      - 127.0.0.1:7657:7657  # router console
      - CHANGEME:12345/tcp  # I2NP protocol
      - CHANGEME:12345/udp  # I2NP protocol

    environment:
      - EXT_PORT=CHANGEME
    labels:
      - "com.centurylinklabs.watchtower.scope=goodkarmakit"


```

But I couldn't make it work, I think because of weird firewall issues.

Would you mind testing it for me?
